#!/usr/bin/env python3
"""Regenerate lib/features/gallery/data/services/label_map.dart from the
canonical ImageNet-1k class list (torchvision / WordNet synset order).

The order MUST match what tool/export_classifier.py bakes in: it exports
`timm.create_model("mobileone_s2", pretrained=True, num_classes=1000)`, whose
output logits are indexed in the official ImageNet-1k class order (0=tench …
999=toilet tissue). A previous hand-written map put classes at invented
indices — every AI label shipped wrong (cats at 281-285 were mapped to
'shed'/'garage'/'tent'). Never edit label_map.dart by hand; regenerate:

    python tool/gen_label_map.py            # use the committed snapshot
    python tool/gen_label_map.py --fetch    # re-download, verify, regenerate

Source: https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a
(class_idx -> human names, in torchvision order). Each entry is stored under
its FIRST common name, e.g. "tabby, tabby cat" -> "tabby".
"""
import argparse
import ast
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "tool" / "imagenet1000_clsidx_to_labels.txt"
OUT = ROOT / "lib" / "features" / "gallery" / "data" / "services" / "label_map.dart"
GIST_RAW_URL = (
    "https://gist.githubusercontent.com/yrevar/942d3a0ac09ec9e5eb3a/raw"
)

# Anchors that must hold for the list to be the canonical torchvision-order
# one. The first block was verified against the canonical reference this
# session (0/1/2/10/207/281-285/291/292/999 are the well-known positions:
# tench…brambling…golden retriever…the five cat classes…toilet tissue);
# the rest are regression anchors pinning the committed snapshot's shape.
ANCHORS = {
    0: "tench",
    1: "goldfish",
    2: "great white shark",
    3: "tiger shark",
    4: "hammerhead",
    6: "stingray",
    10: "brambling",
    11: "goldfinch",
    12: "house finch",
    207: "golden retriever",
    228: "komondor",
    281: "tabby",
    282: "tiger cat",
    283: "Persian cat",
    284: "Siamese cat",
    285: "Egyptian cat",
    291: "lion",
    292: "tiger",
    300: "tiger beetle",
    388: "giant panda",
    408: "amphibian",
    675: "moving van",
    717: "pickup",
    755: "radio telescope",
    817: "sports car",
    968: "cup",
    999: "toilet tissue",
}


def clean(name: str) -> str:
    """First common name of a comma-separated WordNet synonym list."""
    return name.split(",")[0].strip()


def dart_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--fetch",
        action="store_true",
        help="re-download the canonical list before generating",
    )
    args = ap.parse_args()

    if args.fetch:
        print(f"fetching {GIST_RAW_URL}")
        with urllib.request.urlopen(GIST_RAW_URL, timeout=30) as r:
            SNAPSHOT.write_bytes(r.read())
        print(f"wrote {SNAPSHOT}")

    text = SNAPSHOT.read_text(encoding="utf-8")
    raw = ast.literal_eval(text)
    if not isinstance(raw, dict) or sorted(raw) != list(range(1000)):
        print(f"FAIL: expected dict of keys 0..999, got {len(raw)} entries",
              file=sys.stderr)
        return 1

    labels = {i: clean(str(raw[i])) for i in range(1000)}
    for idx, expected in ANCHORS.items():
        got = labels[idx]
        if got != expected:
            print(
                f"FAIL: anchor {idx}: got {got!r}, expected {expected!r} — "
                "the list is not canonical torchvision order",
                file=sys.stderr,
            )
            return 1
    empty = [i for i, v in labels.items() if not v]
    if empty:
        print(f"FAIL: empty names at {empty}", file=sys.stderr)
        return 1

    entries = "\n".join(
        f"  {i}: '{dart_escape(labels[i])}'," for i in range(1000)
    )
    OUT.write_text(
        "/// Maps ImageNet-1k class indices (0-999) to human-readable names in\n"
        "/// the official torchvision/WordNet order — the order produced by the\n"
        "/// model exported through tool/export_classifier.py\n"
        '/// (timm "mobileone_s2", pretrained, 1000 classes).\n'
        "///\n"
        "/// GENERATED by tool/gen_label_map.py — do not hand-edit.\n"
        "/// Indices outside this order mislabel every photo (the hand-written\n"
        '/// map this replaced put cats 281-285 at "shed"/"garage"/"tent").\n'
        "/// Values keep the canonical capitalization; consumers lowercase.\n"
        "const Map<int, String> imageNetLabels = {\n"
        f"{entries}\n"
        "};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({len(labels)} entries, anchors verified)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
