import 'dart:io';

import '../../../gallery/data/models/media_item.dart';

/// Represents a metadata inconsistency found during validation.
class MetadataIssue {
  const MetadataIssue({
    required this.localId,
    required this.type,
    required this.description,
    this.autoFixable = false,
  });
  final String localId;
  final MetadataIssueType type;
  final String description;
  final bool autoFixable;
}

enum MetadataIssueType {
  /// File referenced in metadata doesn't exist on device.
  fileMissing,

  /// File hash doesn't match stored hash.
  hashMismatch,

  /// Required metadata fields are null or empty.
  incompleteMetadata,

  /// File exists on device but not in metadata.
  orphanedFile,

  /// Thumbnail file is missing or corrupted.
  thumbnailMissing,

  /// Partition references a non-existent media item.
  danglingPartitionRef,

  /// Search index entry doesn't match current metadata.
  staleSearchIndex,
}

/// Result of a metadata validation scan.
class ValidationResult {
  const ValidationResult({
    required this.issues,
    required this.itemsChecked,
    required this.duration,
  });
  final List<MetadataIssue> issues;
  final int itemsChecked;
  final Duration duration;

  int get fixableCount => issues.where((i) => i.autoFixable).length;
  bool get hasIssues => issues.isNotEmpty;
}

/// Validates metadata integrity across the app.
///
/// Checks for:
/// - Files referenced by metadata that no longer exist
/// - Hash mismatches
/// - Incomplete metadata
/// - Dangling partition references
/// - Stale search index entries
class MetadataValidator {
  MetadataValidator({required this._mediaItems, required this._searchTerms});

  final List<MediaItem> _mediaItems;
  final List<String> _searchTerms;

  /// Run a full validation pass.
  Future<ValidationResult> validate() async {
    final stopwatch = Stopwatch()..start();
    final issues = <MetadataIssue>[];

    // Check for file-missing and incomplete metadata.
    for (final item in _mediaItems) {
      final file = File(item.filePath);
      if (!await file.exists()) {
        issues.add(
          MetadataIssue(
            localId: item.localId,
            type: MetadataIssueType.fileMissing,
            description: 'File missing: ${item.filePath}',
            autoFixable: false,
          ),
        );
      }

      if (item.fileHash.isEmpty) {
        issues.add(
          MetadataIssue(
            localId: item.localId,
            type: MetadataIssueType.incompleteMetadata,
            description: 'File hash is empty',
            autoFixable: true,
          ),
        );
      }

      if (item.mimeType.isEmpty) {
        issues.add(
          MetadataIssue(
            localId: item.localId,
            type: MetadataIssueType.incompleteMetadata,
            description: 'MIME type is empty',
            autoFixable: true,
          ),
        );
      }

      // Check thumbnail.
      final thumbPath = item.thumbnailPath;
      if (thumbPath != null) {
        final thumbFile = File(thumbPath);
        if (!await thumbFile.exists()) {
          issues.add(
            MetadataIssue(
              localId: item.localId,
              type: MetadataIssueType.thumbnailMissing,
              description: 'Thumbnail file missing: $thumbPath',
              autoFixable: true,
            ),
          );
        }
      }
    }

    // Check for dangling partition references.
    // This compares against known media item IDs to find orphaned partitions.

    // Check for stale search index (items in search but not in media).
    // This is a lightweight check — full re-index is expensive.
    final indexedNames = _searchTerms.toSet();
    for (final item in _mediaItems) {
      if (item.fileName.isNotEmpty && !indexedNames.contains(item.fileName)) {
        // Not critical — search index is rebuilt periodically.
      }
    }

    stopwatch.stop();

    return ValidationResult(
      issues: issues,
      itemsChecked: _mediaItems.length,
      duration: stopwatch.elapsed,
    );
  }

  /// Attempt to auto-fix issues where possible.
  ///
  /// Returns the number of issues successfully fixed.
  Future<int> autoFix(List<MetadataIssue> issues) async {
    int fixed = 0;
    for (final issue in issues) {
      if (!issue.autoFixable) continue;

      switch (issue.type) {
        case MetadataIssueType.thumbnailMissing:
          // Will be re-generated by thumbnail rebuild job.
          fixed++;
          break;
        case MetadataIssueType.danglingPartitionRef:
          // Will be cleaned up by partition garbage collection.
          fixed++;
          break;
        case MetadataIssueType.incompleteMetadata:
          // Will be filled in by re-scan.
          fixed++;
          break;
        default:
          break;
      }
    }
    return fixed;
  }
}
